export const tracks = { 
    'ELECTRO-HOUSE': { 
        url: '/sounds/antrix_01_130_bpm.mp3', 
        bpm: 130,
        artist: 'Antrix', 
        colorA: '#00F2FF', 
        colorB: '#7000FF',
        title: 'Electro House',
        desc: 'Emerging from the early 2000s European club scene, this style weaponizes traditional house beats with gritty, "dirty" bass distortion and aggressive sawtooth synths for high-energy dancefloors.',
        spotify: 'https://open.spotify.com/intl-de/track/1LZlaPjfULtnDNnUq29dfT?si=c5900c79a5914a03',
        PosFreq: 0.152,
        WarpFreq: 1.174,
        AudioStrength: 1.8,
    },
    'HYPERPOP': { 
        url: '/sounds/antrix_02_94_bpm.mp3', 
        bpm: 94, 
        artist: 'Antrix',
        colorA: '#FF007A', 
        colorB: '#00FFD1',
        title: 'Hyperpop',
        desc: 'A 2010s internet-born movement (pioneered by the PC Music collective) that satirizes mainstream pop by inflating its melodies with extreme digital "glitch" textures and pitch-shifted vocals.',
        spotify: 'https://open.spotify.com/intl-de/artist/79zdbhO5VPbya23Nkj7Apr?si=ROYiXbSAQu66cOizkUC8eg',
        PosFreq: 0.119,
        WarpFreq: 1.044,
        AudioStrength: 1.8,
    },
    'TECHNO': { 
        url: '/sounds/paz_01_143_bpm.mp3', 
        bpm: 148, 
        artist: 'Paz',
        colorA: '#FF3E00', 
        colorB: '#111111',
        title: 'Techno',
        desc: 'Born in 1980s Detroit, this is a minimalist, industrial exploration of the "man-machine" relationship, using repetitive 4/4 beats to create a hypnotic, futuristic trance state.',
        spotify: 'https://open.spotify.com/artist/0a4o5fgKVngFrixvuF1OsY?si=mQjQ-J55Qj-PXRuzI2GJYA',
        PosFreq: 1.239,
        WarpFreq: 0,
        AudioStrength: 6.4,
    },
    'DnB': { 
        url: '/sounds/kaos_01_174_bpm.mp3', 
        bpm: 174, 
        artist: 'Kaos Music - Triester',
        colorA: '#00FF41', 
        colorB: '#6600ff',
        title: 'Drum & Bass',
        desc: 'A product of 1990s UK rave culture, it evolved from Jungle by stripping back the samples to focus on high-speed "breakbeat" percussion (160–180 BPM) and earth-shaking sub-bass.',
        spotify: 'https://open.spotify.com/intl-de/track/2ZdP5EmexMAjd2Pr35QFnr?si=745f4647b805406f',
        PosFreq: 0.476,
        WarpFreq: 0.541,
        AudioStrength: 2.1,
    } 
}

